invitations/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^(\d+)/$', 'invitations.views.view_invitation', name='view_invitation'),
    url(r'^(\d+)/add_message$', 'invitations.views.add_message', name='add_message'),
    url(r'^new$', 'invitations.views.new_invitation', name='new_invitation'),
)

sportevents/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'invitations.views.home_page', name='home'),
    url(r'^invitations/', include('invitations.urls')),
    #url(r'^admin/', include(admin.site.urls)),
)

invitations/models.py
from django.db import models


class Invitation(models.Model):
    pass    

class Message(models.Model):
    text = models.TextField(default='')
    invitation = models.ForeignKey(Invitation, default=None)

invitations/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Message, Invitation

# Create your views here.
def home_page(request):             
    return render(request, 'home.html')
    

def view_invitation(request, invitation_id):
    invitation = Invitation.objects.get(id=invitation_id)    
    return render(request, 'invitation.html', {'invitation': invitation})
    

def new_invitation(request):
    invitation = Invitation.objects.create()
    Message.objects.create(text=request.POST['message'], invitation=invitation)
    return redirect('/invitations/%d/' % (invitation.id,))


def add_message(request, invitation_id):
    invitation = Invitation.objects.get(id=invitation_id)
    Message.objects.create(text=request.POST['message'], invitation=invitation)
    return redirect('/invitations/%d/' % (invitation.id))

invitations/templates/home.html
<html>
    <title>Organizujte svoje sportske aktivnosti</title>
    <body>
        <h1>Organizujte svoje sportske aktivnosti</h1>               
        <form method="POST" action="/invitations/new">
            {% csrf_token %}
            <input name="message" id="id_new_message" placeholder="Enter an invitation message" />
        </form>
    </body>    
</html>

invitations/templates/invitation.html
<html>
    <title>Organizujte svoje sportske aktivnosti</title>
    <body>
        <h1>Organizujte svoje sportske aktivnosti</h1>        
        <ul id="id_ul_comments">
            {% for message in invitation.message_set.all %}
                <li>{{ message.text }}</li>
            {% endfor %}                
        </ul>
        <form method="POST" action="/invitations/{{ invitation.id }}/add_message">
            {% csrf_token %}
            <input name="message" id="id_new_message" placeholder="Enter an invitation message" />
        </form>
    </body>    
</html>